services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile

    ports:
      - "8080:8080"

    env_file:
      - ./.env

    restart: unless-stopped # Tự khởi động lại app trừ khi bạn chủ động stop
